version: '3.8'

services: 
    tutorial-api:
        build: 
            context: ./api
            args: 
                jar: ./target/tutorial-api.jar
            dockerfile: Dockerfile
        image: tutorial-api:2.2.0
        container_name: tutorial-api
        ports: 
            - "3000:3000"
        volumes: 
            - api:/tmp
        networks: 
            - tutorial
        environment: 
            TZ: "Asia/Bangkok"

volumes: 
    api:
        driver: local

networks: 
    tutorial:
        driver: bridge

