server:
  port: 3004
  servlet:
    context-path: /tutorial

spring:
  datasource-mysql:
    url: jdbc:mysql://localhost:3306/sys?useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
  datasource-postgres:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver 
    initialization-mode: always