server:
  port: 3004
  servlet:
    context-path: /tutorial

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql